# Some may be not available across all distributions

cli_utils:
  - fd
  - fzf
  - git
  - vim
  - stow
  - htop
  - tlrc
  - tmux
  - httpie
  - zoxide

mac_cli_utils:
  - uv
  - mas

common_pkgs:
  - zed
  - ghostty

macos_pkgs:
  - vlc
  - flux
  - stats
  - raycast
  - spotify
  - aldente
  - calibre
  - itsycal
  - telegram
  - protonvpn
  - bitwarden
  - oversight
  - todoist-app
  - app-cleaner
  - proton-mail
  - proton-drive
  - google-drive
  - logi-options+
  - wireshark-app
  - jordanbaird-ice

# mas_apps:
#   - 937984704
#   - 302584613
  # - 585829637
  # - 1596283165
  # - 1398373917
  # - 585829637

mac_taps:
  - buo/cask-upgrade
  
# linux_packages:
#   - test
