- name: Update Brew and packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install packages
  community.general.homebrew_cask:
    name: "{{ mac_packages + common_packages }}"
    state: present

- name: Install cli utils
  community.general.homebrew:
    name: "{{ cli_utils }}"
    state: present

- name: Brew tap
  community.general.homebrew_tap:
    name: "{{ mac_taps }}"
    state: present