- name: Update Brew and packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install Brew packages via Brewfile
  command: brew bundle install --file Brewfile.base
  args:
    chdir: "{{ playbook_dir }}/files/brew"
  register: brew_bundle
  failed_when: brew_bundle.rc != 0
